### ISSUE TITLE
gpgkey handling fix in 0.5.2 makes most repositories gpgkeys download fail

### ISSUE THREAD

**Issue by CGForeau** [Ayowel/rpm-manager#9]
The recent change to better handle multiline gpgkey definitions makes download fail when there is no space between the `=` signe and the first file (subsequent files are properly loaded though). This is due to adding -E to `sed` without removing the `\` in `\|`

https://github.com/Ayowel/rpm-manager/blob/6ad9c720865a801685b8cb62ba56bc4d3cfcd573/src/download.sh#L347

**Comment by Ayowel** [comment]
Fix applied in 37bedc0be61c0f4d6460cd27ad0c87acbbba24f3 . Added tests to ensure it does not happen again.
